/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/*\title Multicore LED control
 * \abstract One LED is controlled by using three different cores.
 * \description Core 0 is switching on an LED. When the LED flag is set, Core 1 is switching off the LED.
 *              Core 2 is controlling the state of the LED flag.
 *
 * \name Multicore_1_KIT_TC397_TFT
 * \version V1.0.1
 * \board APPLICATION KIT TC3X7 V2.0, KIT_A2G_TC397_5V_TFT, TC39xXX_B-Step
 * \keywords multicore, LED, AURIX, Multicore_1
 * \documents https://www.infineon.com/aurix-expert-training/Infineon-AURIX_Multicore_1_KIT_TC397_TFT-TR-v01_00_01-EN.pdf
 * \documents https://www.infineon.com/aurix-expert-training/TC39B_iLLD_UM_1_0_1_12_1.chm
 * \lastUpdated 2020-12-18
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "pub.h"
#include "lwip_demo.h"

IFX_ALIGN(4)
IfxCpu_syncEvent g_cpuSyncEvent = 0;


/**
 * @brief 
 * 
 * @param times 
 */
void instruct_delay(int times)
{
    int delay_nums = 0;
    for (int i = 0; i < times; i++)
    {
        delay_nums = 50000000;
        while (delay_nums--)
            ;
    }
}

BaseType_t ret0 = 0, ret1 = 0, ret2 = 0;
void core0_main(void)
{
    BaseType_t xReturn;
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    initLEDs();
    //initTime();

    initShellInterface();

    Ifx_print("hello Tc397!\r\n");

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    g_eth_swamphore = xSemaphoreCreateCounting(10, 0);
    g_can0_swamphore = xSemaphoreCreateCounting(10, 0);
    g_can2_swamphore = xSemaphoreCreateCounting(10, 0);

#ifdef ETH_TEST_CPU0
    //xTaskCreate(test_eth_fos, "test_eth_fos", 1024, NULL, 3, NULL);
    ret0 = xTaskCreate(test_eth_socket_client_fos, "test_eth_socket_client_fos", 1024, NULL, 3, NULL);
    ret1 = xTaskCreate(test_eth_socket_server_fos, "test_eth_socket_server_fos", 1024, NULL, 4, NULL);
    /*eth Must be at the highest level of the running task*/
    ret2 = xTaskCreate(eth_init_fos, "eth_init_fos", 2048, NULL, 5, NULL);
#endif

#ifdef CAN_TEST_CPU0
    can_init(0);
    can_init(2);
    xReturn = xTaskCreate(test_can0_send_cpu0, "test0_cpu0", 512, NULL, 3, NULL);
    xReturn = xTaskCreate(test_can0_recv_cpu0, "test1_cpu0", 512, NULL, 3, NULL);
    xReturn = xTaskCreate(test_can2_send_cpu0, "test2_cpu0", 512, NULL, 3, NULL);
    xReturn = xTaskCreate(test_can2_recv_cpu0, "test3_cpu0", 512, NULL, 3, NULL);
#endif

    vTaskStartScheduler();

    while (1)
    {
        Ifx_print("never here!\r\n");
    }
}
